<?xml version="1.0" encoding="utf-8"?><Database Name="DiversityCollection_BaseTest" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=141.84.65.107,5432;Initial Catalog=DiversityCollection_BaseTest;Persist Security Info=True;User ID=Rollinger" SettingsObjectName="LinqToSQL.Properties.Settings" SettingsPropertyName="DiversityCollection_BaseTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.IdentificationUnit" Member="IdentificationUnit">
    <Type Name="IdentificationUnit">
      <Column Name="CollectionSpecimenID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdentificationUnitID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LastIdentificationCache" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="FamilyCache" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="OrderCache" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TaxonomicGroup" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OnlyObserved" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RelatedUnitID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RelationType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ColonisedSubstratePart" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LifeStage" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NumberOfUnits" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ExsiccataNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExsiccataIdentification" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="UnitIdentifier" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UnitDescription" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Circumstances" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LogCreatedWhen" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LogCreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LogUpdatedWhen" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LogUpdatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="xx_SubstrateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="xx_SubstrateRelationType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="xx_SpecimenPartID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="xx_NewUnitID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="xx_AlteUnitID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RowGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>