//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityPhone {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DiversityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiversityResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiversityPhone.Properties.DiversityResources", typeof(DiversityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Analysis.
        /// </summary>
        public static string Analysis_NoAnalysis {
            get {
                return ResourceManager.GetString("Analysis_NoAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Result.
        /// </summary>
        public static string Analysis_Result_NoResult {
            get {
                return ResourceManager.GetString("Analysis_Result_NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This App was implemented by.
        /// </summary>
        public static string App_CreatedBy {
            get {
                return ResourceManager.GetString("App_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Tobias Schneider and Georg Rollinger 
        ///University of Bayreuth
        ///Chair for Applied Computer Science IV 
        ///under supervision of Prof. Dr.-Ing. Stefan Jablonski..
        /// </summary>
        public static string App_Credits {
            get {
                return ResourceManager.GetString("App_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string App_Homepage_Title {
            get {
                return ResourceManager.GetString("App_Homepage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.diversitymobile.net.
        /// </summary>
        public static string App_Homepage_URL {
            get {
                return ResourceManager.GetString("App_Homepage_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiversityMobile – recording biological research data in nature
        ///
        ///DiversityMobile is an application for professional biologists and ecologists as well as citizen scientists, being experienced in recording observation data in nature. Information may be directly entered into the smartphone database. DiversityMobile is designed following Diversity Workbench (=DWB) concepts. Mechanisms of automated recording and storage of GPS data and the manual recording of multimedia data are included. During that process th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string App_Info {
            get {
                return ResourceManager.GetString("App_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diversitymobile@bsm.mwn.de.
        /// </summary>
        public static string App_Mail_Address {
            get {
                return ResourceManager.GetString("App_Mail_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string App_Mail_Title {
            get {
                return ResourceManager.GetString("App_Mail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diversity Mobile Wiki.
        /// </summary>
        public static string App_Map_LinkTitle {
            get {
                return ResourceManager.GetString("App_Map_LinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SNSB IT Center offers a user-restricted web service to use ‘TK25 Bayern Topographische Karten’ for the DiversityMobile WP app. The digital maps are provided to DiversityMobile users by the Bayerische Vermessungsverwaltunghttp://vermessung.bayern.de/index.html). For detail information about these maps and the license that governs their use visit the.
        /// </summary>
        public static string App_Map_Text {
            get {
                return ResourceManager.GetString("App_Map_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.diversitymobile.net/wiki/TK25_Maps_Bavaria_for_DiversityMobile.
        /// </summary>
        public static string App_Map_URL {
            get {
                return ResourceManager.GetString("App_Map_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diversity Mobile Wiki.
        /// </summary>
        public static string App_Taxa_LinkTitle {
            get {
                return ResourceManager.GetString("App_Taxa_LinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SNSB IT Center offers web services with open and free read-only access to taxon lists and scientific terminologies in the DWB context. This data is provided in cooperation with the Bayerische Landesamt für Umwelt (http://www.lfu.bayern.de/index.htm), with several diversity research projects and individual scientists. For details visit the .
        /// </summary>
        public static string App_Taxa_Text {
            get {
                return ResourceManager.GetString("App_Taxa_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxon Names.
        /// </summary>
        public static string App_Taxa_Title {
            get {
                return ResourceManager.GetString("App_Taxa_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.diversitymobile.net/wiki/TNT_services_for_DiversityMobile.
        /// </summary>
        public static string App_Taxa_URL {
            get {
                return ResourceManager.GetString("App_Taxa_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string Button_Play {
            get {
                return ResourceManager.GetString("Button_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string Button_Stop {
            get {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string Download_DownloadingItems {
            get {
                return ResourceManager.GetString("Download_DownloadingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event already downloaded.
        /// </summary>
        public static string Download_EventAlreadyDownloaded {
            get {
                return ResourceManager.GetString("Download_EventAlreadyDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel download.
        /// </summary>
        public static string Download_Header_CancelDownload {
            get {
                return ResourceManager.GetString("Download_Header_CancelDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location query.
        /// </summary>
        public static string Download_Header_LocationQuery {
            get {
                return ResourceManager.GetString("Download_Header_LocationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to press and hold to download an item.
        /// </summary>
        public static string Download_HintLongPress {
            get {
                return ResourceManager.GetString("Download_HintLongPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Done.
        /// </summary>
        public static string Download_ItemsDone {
            get {
                return ResourceManager.GetString("Download_ItemsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for Events ....
        /// </summary>
        public static string Download_SearchingEvents {
            get {
                return ResourceManager.GetString("Download_SearchingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string EventProperty_Header_Property {
            get {
                return ResourceManager.GetString("EventProperty_Header_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string EventProperty_Header_Value {
            get {
                return ResourceManager.GetString("EventProperty_Header_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Altitude.
        /// </summary>
        public static string GeoCoordinates_NoAltitude {
            get {
                return ResourceManager.GetString("GeoCoordinates_NoAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Latitude.
        /// </summary>
        public static string GeoCoordinates_NoLatitude {
            get {
                return ResourceManager.GetString("GeoCoordinates_NoLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Longitude.
        /// </summary>
        public static string GeoCoordinates_NoLongitude {
            get {
                return ResourceManager.GetString("GeoCoordinates_NoLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string GeoCoordinates_Suffix_E {
            get {
                return ResourceManager.GetString("GeoCoordinates_Suffix_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string GeoCoordinates_Suffix_Meter {
            get {
                return ResourceManager.GetString("GeoCoordinates_Suffix_Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string GeoCoordinates_Suffix_N {
            get {
                return ResourceManager.GetString("GeoCoordinates_Suffix_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string GeoCoordinates_Suffix_S {
            get {
                return ResourceManager.GetString("GeoCoordinates_Suffix_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string GeoCoordinates_Suffix_W {
            get {
                return ResourceManager.GetString("GeoCoordinates_Suffix_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add series.
        /// </summary>
        public static string Home_Header_ButtonAdd {
            get {
                return ResourceManager.GetString("Home_Header_ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maps.
        /// </summary>
        public static string Home_Header_ButtonMaps {
            get {
                return ResourceManager.GetString("Home_Header_ButtonMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Home_Header_ButtonSettings {
            get {
                return ResourceManager.GetString("Home_Header_ButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open a new Series while there is still an unfinished one..
        /// </summary>
        public static string Home_Info_CantOpenNewSeries {
            get {
                return ResourceManager.GetString("Home_Info_CantOpenNewSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Date.
        /// </summary>
        public static string IdentificationUnit_Header_AnalysisDate {
            get {
                return ResourceManager.GetString("IdentificationUnit_Header_AnalysisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        public static string IdentificationUnit_Header_Identification {
            get {
                return ResourceManager.GetString("IdentificationUnit_Header_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Query.
        /// </summary>
        public static string IdentificationUnit_Header_NameQuery {
            get {
                return ResourceManager.GetString("IdentificationUnit_Header_NameQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only observed.
        /// </summary>
        public static string IdentificationUnit_Header_OnlyObserved {
            get {
                return ResourceManager.GetString("IdentificationUnit_Header_OnlyObserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification.
        /// </summary>
        public static string IdentificationUnit_Header_Qualification {
            get {
                return ResourceManager.GetString("IdentificationUnit_Header_Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Type.
        /// </summary>
        public static string IdentificationUnit_Header_RelationshipType {
            get {
                return ResourceManager.GetString("IdentificationUnit_Header_RelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomic Group.
        /// </summary>
        public static string IdentificationUnit_Header_TaxonomicGroup {
            get {
                return ResourceManager.GetString("IdentificationUnit_Header_TaxonomicGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Analyses available..
        /// </summary>
        public static string IdentificationUnit_Info_NoAnalyses {
            get {
                return ResourceManager.GetString("IdentificationUnit_Info_NoAnalyses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item can not be changed, it has already been uploaded..
        /// </summary>
        public static string Info_CantEditItem {
            get {
                return ResourceManager.GetString("Info_CantEditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to press and hold to display menu.
        /// </summary>
        public static string Info_ContextMenu {
            get {
                return ResourceManager.GetString("Info_ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Objects ....
        /// </summary>
        public static string Info_DeletingObjects {
            get {
                return ResourceManager.GetString("Info_DeletingObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Info_MissingRights {
            get {
                return ResourceManager.GetString("Info_MissingRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connectivity.
        /// </summary>
        public static string Info_NoInternet {
            get {
                return ResourceManager.GetString("Info_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Wifi connectivity available, online services disabled.
        /// </summary>
        public static string Info_NoWifi {
            get {
                return ResourceManager.GetString("Info_NoWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Unavailable.
        /// </summary>
        public static string Info_ServiceUnavailable {
            get {
                return ResourceManager.GetString("Info_ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t download the Map. Maybe you don&apos;t have permissions to do that?.
        /// </summary>
        public static string MapManagement_Message_NoPermissions {
            get {
                return ResourceManager.GetString("MapManagement_Message_NoPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this element and all its children?.
        /// </summary>
        public static string Message_ConfirmDelete {
            get {
                return ResourceManager.GetString("Message_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal Exception has occurred, please report this to your administrator:.
        /// </summary>
        public static string Message_FatalException {
            get {
                return ResourceManager.GetString("Message_FatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred while processing your request. Maybe you don&apos;t have sufficient permissions. Message:.
        /// </summary>
        public static string Message_ServiceProblem {
            get {
                return ResourceManager.GetString("Message_ServiceProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        public static string Message_SorryHeader {
            get {
                return ResourceManager.GetString("Message_SorryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning the Database.
        /// </summary>
        public static string RefreshVocabularyTask_State_Cleaning {
            get {
                return ResourceManager.GetString("RefreshVocabularyTask_State_Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Analyses.
        /// </summary>
        public static string RefreshVocabularyTask_State_LoadingAnalyses {
            get {
                return ResourceManager.GetString("RefreshVocabularyTask_State_LoadingAnalyses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Event Properties.
        /// </summary>
        public static string RefreshVocabularyTask_State_LoadingProperties {
            get {
                return ResourceManager.GetString("RefreshVocabularyTask_State_LoadingProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Qualifications.
        /// </summary>
        public static string RefreshVocabularyTask_State_LoadingQualifications {
            get {
                return ResourceManager.GetString("RefreshVocabularyTask_State_LoadingQualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Analysis Results.
        /// </summary>
        public static string RefreshVocabularyTask_State_LoadingResults {
            get {
                return ResourceManager.GetString("RefreshVocabularyTask_State_LoadingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Vocabulary.
        /// </summary>
        public static string RefreshVocabularyTask_State_LoadingVocabulary {
            get {
                return ResourceManager.GetString("RefreshVocabularyTask_State_LoadingVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear db.
        /// </summary>
        public static string Settings_Header_ButtonClear {
            get {
                return ResourceManager.GetString("Settings_Header_ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get vocabulary.
        /// </summary>
        public static string Settings_Header_ButtonRefresh {
            get {
                return ResourceManager.GetString("Settings_Header_ButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Settings_Header_ButtonSave {
            get {
                return ResourceManager.GetString("Settings_Header_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Data.
        /// </summary>
        public static string Settings_Header_DownloadData {
            get {
                return ResourceManager.GetString("Settings_Header_DownloadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Settings_Header_Info {
            get {
                return ResourceManager.GetString("Settings_Header_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Taxon Lists.
        /// </summary>
        public static string Settings_Header_ManageTaxa {
            get {
                return ResourceManager.GetString("Settings_Header_ManageTaxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Data.
        /// </summary>
        public static string Settings_Header_UploadData {
            get {
                return ResourceManager.GetString("Settings_Header_UploadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Setup_Header_ButtonSave {
            get {
                return ResourceManager.GetString("Setup_Header_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Setup_Header_Password {
            get {
                return ResourceManager.GetString("Setup_Header_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Setup_Header_Project {
            get {
                return ResourceManager.GetString("Setup_Header_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string Setup_Header_Repository {
            get {
                return ResourceManager.GetString("Setup_Header_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Setup_Header_Username {
            get {
                return ResourceManager.GetString("Setup_Header_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Projects.
        /// </summary>
        public static string Setup_Info_GettingProjects {
            get {
                return ResourceManager.GetString("Setup_Info_GettingProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Repositories.
        /// </summary>
        public static string Setup_Info_GettingRepositories {
            get {
                return ResourceManager.GetString("Setup_Info_GettingRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credentials.
        /// </summary>
        public static string Setup_Info_InvalidCredentials {
            get {
                return ResourceManager.GetString("Setup_Info_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose.
        /// </summary>
        public static string Setup_Item_PleaseChoose {
            get {
                return ResourceManager.GetString("Setup_Item_PleaseChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to allow DiversityMobile to use your current location information? This information would be used for the localization of data you enter. This information would then be sent to the SNSB servers once you start the upload of that data. You can always change this behavior in the settings..
        /// </summary>
        public static string Setup_Message_AllowGPS_Body {
            get {
                return ResourceManager.GetString("Setup_Message_AllowGPS_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Location Data?.
        /// </summary>
        public static string Setup_Message_AllowGPS_Caption {
            get {
                return ResourceManager.GetString("Setup_Message_AllowGPS_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only use the application once it&apos;s been initialized.
        /// </summary>
        public static string Setup_Message_CantGoBack_Body {
            get {
                return ResourceManager.GetString("Setup_Message_CantGoBack_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload all.
        /// </summary>
        public static string Sync_Dialog_UploadAll_Caption {
            get {
                return ResourceManager.GetString("Sync_Dialog_UploadAll_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to upload all new Multimedia? Only do this if the Phone is charging and connected via Wifi..
        /// </summary>
        public static string Sync_Dialog_UploadAll_Text {
            get {
                return ResourceManager.GetString("Sync_Dialog_UploadAll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Upload.
        /// </summary>
        public static string Sync_Header_CancelUpload {
            get {
                return ResourceManager.GetString("Sync_Header_CancelUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data.
        /// </summary>
        public static string Sync_Header_Data {
            get {
                return ResourceManager.GetString("Sync_Header_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multimedia.
        /// </summary>
        public static string Sync_Header_Multimedia {
            get {
                return ResourceManager.GetString("Sync_Header_Multimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync level.
        /// </summary>
        public static string Sync_Header_SyncLevel {
            get {
                return ResourceManager.GetString("Sync_Header_SyncLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting Modifications.
        /// </summary>
        public static string Sync_Info_CollectingModifications {
            get {
                return ResourceManager.GetString("Sync_Info_CollectingModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting Multimedia.
        /// </summary>
        public static string Sync_Info_CollectingMultimedia {
            get {
                return ResourceManager.GetString("Sync_Info_CollectingMultimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading ....
        /// </summary>
        public static string Sync_Info_Uploading {
            get {
                return ResourceManager.GetString("Sync_Info_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string Sync_Info_UploadingElement {
            get {
                return ResourceManager.GetString("Sync_Info_UploadingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Multimedia ....
        /// </summary>
        public static string Sync_Info_UploadingMultimedia {
            get {
                return ResourceManager.GetString("Sync_Info_UploadingMultimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Sync_Level_All {
            get {
                return ResourceManager.GetString("Sync_Level_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Sync_Level_Event {
            get {
                return ResourceManager.GetString("Sync_Level_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventSeries.
        /// </summary>
        public static string Sync_Level_EventSeries {
            get {
                return ResourceManager.GetString("Sync_Level_EventSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification Unit.
        /// </summary>
        public static string Sync_Level_IU {
            get {
                return ResourceManager.GetString("Sync_Level_IU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specimen.
        /// </summary>
        public static string Sync_Level_Specimen {
            get {
                return ResourceManager.GetString("Sync_Level_Specimen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t download another taxon list..
        /// </summary>
        public static string TaxonManagement_Message_CantDownload {
            get {
                return ResourceManager.GetString("TaxonManagement_Message_CantDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TaxonManagement_Message_Error {
            get {
                return ResourceManager.GetString("TaxonManagement_Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Taxa ....
        /// </summary>
        public static string TaxonManagement_State_DownloadingList {
            get {
                return ResourceManager.GetString("TaxonManagement_State_DownloadingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Taxon Lists ....
        /// </summary>
        public static string TaxonManagement_State_DownloadingLists {
            get {
                return ResourceManager.GetString("TaxonManagement_State_DownloadingLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download all.
        /// </summary>
        public static string TaxonManagement_Title_DownloadAll {
            get {
                return ResourceManager.GetString("TaxonManagement_Title_DownloadAll", resourceCulture);
            }
        }
    }
}
