//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityPhone {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DiversityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiversityResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiversityPhone.DiversityResources", typeof(DiversityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Analysis.
        /// </summary>
        public static string Analysis_NoAnalysis {
            get {
                return ResourceManager.GetString("Analysis_NoAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Result.
        /// </summary>
        public static string Analysis_Result_NoResult {
            get {
                return ResourceManager.GetString("Analysis_Result_NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string Button_Play {
            get {
                return ResourceManager.GetString("Button_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string Button_Stop {
            get {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string EventProperty_Header_Property {
            get {
                return ResourceManager.GetString("EventProperty_Header_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string EventProperty_Header_Value {
            get {
                return ResourceManager.GetString("EventProperty_Header_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Altitude.
        /// </summary>
        public static string GeoCoordinates_NoAltitude {
            get {
                return ResourceManager.GetString("GeoCoordinates_NoAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Latitude.
        /// </summary>
        public static string GeoCoordinates_NoLatitude {
            get {
                return ResourceManager.GetString("GeoCoordinates_NoLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Longitude.
        /// </summary>
        public static string GeoCoordinates_NoLongitude {
            get {
                return ResourceManager.GetString("GeoCoordinates_NoLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string GeoCoordinates_Suffix_E {
            get {
                return ResourceManager.GetString("GeoCoordinates_Suffix_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string GeoCoordinates_Suffix_Meter {
            get {
                return ResourceManager.GetString("GeoCoordinates_Suffix_Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string GeoCoordinates_Suffix_N {
            get {
                return ResourceManager.GetString("GeoCoordinates_Suffix_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string GeoCoordinates_Suffix_S {
            get {
                return ResourceManager.GetString("GeoCoordinates_Suffix_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string GeoCoordinates_Suffix_W {
            get {
                return ResourceManager.GetString("GeoCoordinates_Suffix_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add series.
        /// </summary>
        public static string Home_Header_ButtonAdd {
            get {
                return ResourceManager.GetString("Home_Header_ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maps.
        /// </summary>
        public static string Home_Header_ButtonMaps {
            get {
                return ResourceManager.GetString("Home_Header_ButtonMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Home_Header_ButtonSettings {
            get {
                return ResourceManager.GetString("Home_Header_ButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open a new Series while there is still an unfinished one..
        /// </summary>
        public static string Home_Info_CantOpenNewSeries {
            get {
                return ResourceManager.GetString("Home_Info_CantOpenNewSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Date.
        /// </summary>
        public static string IdentificationUnit_Header_AnalysisDate {
            get {
                return ResourceManager.GetString("IdentificationUnit_Header_AnalysisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        public static string IdentificationUnit_Header_Identification {
            get {
                return ResourceManager.GetString("IdentificationUnit_Header_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Query.
        /// </summary>
        public static string IdentificationUnit_Header_NameQuery {
            get {
                return ResourceManager.GetString("IdentificationUnit_Header_NameQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only observed.
        /// </summary>
        public static string IdentificationUnit_Header_OnlyObserved {
            get {
                return ResourceManager.GetString("IdentificationUnit_Header_OnlyObserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification.
        /// </summary>
        public static string IdentificationUnit_Header_Qualification {
            get {
                return ResourceManager.GetString("IdentificationUnit_Header_Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Type.
        /// </summary>
        public static string IdentificationUnit_Header_RelationshipType {
            get {
                return ResourceManager.GetString("IdentificationUnit_Header_RelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomic Group.
        /// </summary>
        public static string IdentificationUnit_Header_TaxonomicGroup {
            get {
                return ResourceManager.GetString("IdentificationUnit_Header_TaxonomicGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Analyses available..
        /// </summary>
        public static string IdentificationUnit_Info_NoAnalyses {
            get {
                return ResourceManager.GetString("IdentificationUnit_Info_NoAnalyses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item can not be changed, it has already been uploaded..
        /// </summary>
        public static string Info_CantEditItem {
            get {
                return ResourceManager.GetString("Info_CantEditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Objects ....
        /// </summary>
        public static string Info_DeletingObjects {
            get {
                return ResourceManager.GetString("Info_DeletingObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connectivity.
        /// </summary>
        public static string Info_NoInternet {
            get {
                return ResourceManager.GetString("Info_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this element and all its children?.
        /// </summary>
        public static string Message_ConfirmDelete {
            get {
                return ResourceManager.GetString("Message_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal Exception has occurred, please report this to your administrator:.
        /// </summary>
        public static string Message_FatalException {
            get {
                return ResourceManager.GetString("Message_FatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is currently unavailable, please try again later.
        /// </summary>
        public static string Message_ServiceUnavailable_Body {
            get {
                return ResourceManager.GetString("Message_ServiceUnavailable_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        public static string Message_SorryHeader {
            get {
                return ResourceManager.GetString("Message_SorryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning the Database.
        /// </summary>
        public static string RefreshVocabularyTask_State_Cleaning {
            get {
                return ResourceManager.GetString("RefreshVocabularyTask_State_Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Analyses.
        /// </summary>
        public static string RefreshVocabularyTask_State_LoadingAnalyses {
            get {
                return ResourceManager.GetString("RefreshVocabularyTask_State_LoadingAnalyses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Event Properties.
        /// </summary>
        public static string RefreshVocabularyTask_State_LoadingProperties {
            get {
                return ResourceManager.GetString("RefreshVocabularyTask_State_LoadingProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Qualifications.
        /// </summary>
        public static string RefreshVocabularyTask_State_LoadingQualifications {
            get {
                return ResourceManager.GetString("RefreshVocabularyTask_State_LoadingQualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Analysis Results.
        /// </summary>
        public static string RefreshVocabularyTask_State_LoadingResults {
            get {
                return ResourceManager.GetString("RefreshVocabularyTask_State_LoadingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Vocabulary.
        /// </summary>
        public static string RefreshVocabularyTask_State_LoadingVocabulary {
            get {
                return ResourceManager.GetString("RefreshVocabularyTask_State_LoadingVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear database.
        /// </summary>
        public static string Settings_Header_ButtonClear {
            get {
                return ResourceManager.GetString("Settings_Header_ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh vocabulary.
        /// </summary>
        public static string Settings_Header_ButtonRefresh {
            get {
                return ResourceManager.GetString("Settings_Header_ButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Settings_Header_ButtonSave {
            get {
                return ResourceManager.GetString("Settings_Header_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Setup_Header_ButtonSave {
            get {
                return ResourceManager.GetString("Setup_Header_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Setup_Header_Project {
            get {
                return ResourceManager.GetString("Setup_Header_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string Setup_Header_Repository {
            get {
                return ResourceManager.GetString("Setup_Header_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Projects.
        /// </summary>
        public static string Setup_Info_GettingProjects {
            get {
                return ResourceManager.GetString("Setup_Info_GettingProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Repositories.
        /// </summary>
        public static string Setup_Info_GettingRepositories {
            get {
                return ResourceManager.GetString("Setup_Info_GettingRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose.
        /// </summary>
        public static string Setup_Item_PleaseChoose {
            get {
                return ResourceManager.GetString("Setup_Item_PleaseChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only use the application once it&apos;s been initialized.
        /// </summary>
        public static string Setup_Message_CantGoBack_Body {
            get {
                return ResourceManager.GetString("Setup_Message_CantGoBack_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload all.
        /// </summary>
        public static string Sync_Dialog_UploadAll_Caption {
            get {
                return ResourceManager.GetString("Sync_Dialog_UploadAll_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to upload all new Multimedia? Only do this if the Phone is charging and connected via Wifi..
        /// </summary>
        public static string Sync_Dialog_UploadAll_Text {
            get {
                return ResourceManager.GetString("Sync_Dialog_UploadAll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data.
        /// </summary>
        public static string Sync_Header_Data {
            get {
                return ResourceManager.GetString("Sync_Header_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multimedia.
        /// </summary>
        public static string Sync_Header_Multimedia {
            get {
                return ResourceManager.GetString("Sync_Header_Multimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t download another taxon list..
        /// </summary>
        public static string TaxonManagement_Message_CantDownload {
            get {
                return ResourceManager.GetString("TaxonManagement_Message_CantDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TaxonManagement_Message_Error {
            get {
                return ResourceManager.GetString("TaxonManagement_Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download all.
        /// </summary>
        public static string TaxonManagement_Title_DownloadAll {
            get {
                return ResourceManager.GetString("TaxonManagement_Title_DownloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Event and children ....
        /// </summary>
        public static string UploadEventTask_State_UploadingEvent {
            get {
                return ResourceManager.GetString("UploadEventTask_State_UploadingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading EventSeries ....
        /// </summary>
        public static string UploadEventTask_State_UploadingSeries {
            get {
                return ResourceManager.GetString("UploadEventTask_State_UploadingSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Multimedia ....
        /// </summary>
        public static string UploadMultimediaTask_State_Uploading {
            get {
                return ResourceManager.GetString("UploadMultimediaTask_State_Uploading", resourceCulture);
            }
        }
    }
}
