//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17626
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityPhone {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DiversityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiversityResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiversityPhone.DiversityResources", typeof(DiversityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Property ähnelt.
        /// </summary>
        public static string EventProperty_Header_Property {
            get {
                return ResourceManager.GetString("EventProperty_Header_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        public static string EventProperty_Header_Value {
            get {
                return ResourceManager.GetString("EventProperty_Header_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Altitude ähnelt.
        /// </summary>
        public static string GeoCoordinates_NoAltitude {
            get {
                return ResourceManager.GetString("GeoCoordinates_NoAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Latitude ähnelt.
        /// </summary>
        public static string GeoCoordinates_NoLatitude {
            get {
                return ResourceManager.GetString("GeoCoordinates_NoLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Longitude ähnelt.
        /// </summary>
        public static string GeoCoordinates_NoLongitude {
            get {
                return ResourceManager.GetString("GeoCoordinates_NoLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E ähnelt.
        /// </summary>
        public static string GeoCoordinates_Suffix_E {
            get {
                return ResourceManager.GetString("GeoCoordinates_Suffix_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die m ähnelt.
        /// </summary>
        public static string GeoCoordinates_Suffix_Meter {
            get {
                return ResourceManager.GetString("GeoCoordinates_Suffix_Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N ähnelt.
        /// </summary>
        public static string GeoCoordinates_Suffix_N {
            get {
                return ResourceManager.GetString("GeoCoordinates_Suffix_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S ähnelt.
        /// </summary>
        public static string GeoCoordinates_Suffix_S {
            get {
                return ResourceManager.GetString("GeoCoordinates_Suffix_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die W ähnelt.
        /// </summary>
        public static string GeoCoordinates_Suffix_W {
            get {
                return ResourceManager.GetString("GeoCoordinates_Suffix_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add series ähnelt.
        /// </summary>
        public static string Home_Header_ButtonAdd {
            get {
                return ResourceManager.GetString("Home_Header_ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die maps ähnelt.
        /// </summary>
        public static string Home_Header_ButtonMaps {
            get {
                return ResourceManager.GetString("Home_Header_ButtonMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die settings ähnelt.
        /// </summary>
        public static string Home_Header_ButtonSettings {
            get {
                return ResourceManager.GetString("Home_Header_ButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t open a new Series while there is still an unfinished one. ähnelt.
        /// </summary>
        public static string Home_Info_CantOpenNewSeries {
            get {
                return ResourceManager.GetString("Home_Info_CantOpenNewSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Identification ähnelt.
        /// </summary>
        public static string IdentificationUnit_Header_Identification {
            get {
                return ResourceManager.GetString("IdentificationUnit_Header_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Analyses available. ähnelt.
        /// </summary>
        public static string IdentificationUnit_Info_NoAnalyses {
            get {
                return ResourceManager.GetString("IdentificationUnit_Info_NoAnalyses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This item can not be changed, it has already been uploaded. ähnelt.
        /// </summary>
        public static string Info_CantEditItem {
            get {
                return ResourceManager.GetString("Info_CantEditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete this element and all its children? ähnelt.
        /// </summary>
        public static string Message_ConfirmDelete {
            get {
                return ResourceManager.GetString("Message_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A fatal Exception has occurred, please report this to your administrator: ähnelt.
        /// </summary>
        public static string Message_FatalException {
            get {
                return ResourceManager.GetString("Message_FatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The service is currently unavailable, please try again later ähnelt.
        /// </summary>
        public static string Message_ServiceUnavailable_Body {
            get {
                return ResourceManager.GetString("Message_ServiceUnavailable_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry ähnelt.
        /// </summary>
        public static string Message_SorryHeader {
            get {
                return ResourceManager.GetString("Message_SorryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cleaning the Database ähnelt.
        /// </summary>
        public static string RefreshVocabularyTask_State_Cleaning {
            get {
                return ResourceManager.GetString("RefreshVocabularyTask_State_Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading Analyses ähnelt.
        /// </summary>
        public static string RefreshVocabularyTask_State_LoadingAnalyses {
            get {
                return ResourceManager.GetString("RefreshVocabularyTask_State_LoadingAnalyses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading Event Properties ähnelt.
        /// </summary>
        public static string RefreshVocabularyTask_State_LoadingProperties {
            get {
                return ResourceManager.GetString("RefreshVocabularyTask_State_LoadingProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading Analysis Results ähnelt.
        /// </summary>
        public static string RefreshVocabularyTask_State_LoadingResults {
            get {
                return ResourceManager.GetString("RefreshVocabularyTask_State_LoadingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading Vocabulary ähnelt.
        /// </summary>
        public static string RefreshVocabularyTask_State_LoadingVocabulary {
            get {
                return ResourceManager.GetString("RefreshVocabularyTask_State_LoadingVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die clear database ähnelt.
        /// </summary>
        public static string Settings_Header_ButtonClear {
            get {
                return ResourceManager.GetString("Settings_Header_ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die refresh vocabulary ähnelt.
        /// </summary>
        public static string Settings_Header_ButtonRefresh {
            get {
                return ResourceManager.GetString("Settings_Header_ButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die save ähnelt.
        /// </summary>
        public static string Settings_Header_ButtonSave {
            get {
                return ResourceManager.GetString("Settings_Header_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die save ähnelt.
        /// </summary>
        public static string Setup_Header_ButtonSave {
            get {
                return ResourceManager.GetString("Setup_Header_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project ähnelt.
        /// </summary>
        public static string Setup_Header_Project {
            get {
                return ResourceManager.GetString("Setup_Header_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository ähnelt.
        /// </summary>
        public static string Setup_Header_Repository {
            get {
                return ResourceManager.GetString("Setup_Header_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please Choose ähnelt.
        /// </summary>
        public static string Setup_Item_PleaseChoose {
            get {
                return ResourceManager.GetString("Setup_Item_PleaseChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can only use the application once it&apos;s been initialized ähnelt.
        /// </summary>
        public static string Setup_Message_CantGoBack_Body {
            get {
                return ResourceManager.GetString("Setup_Message_CantGoBack_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die upload all ähnelt.
        /// </summary>
        public static string Sync_Dialog_UploadAll_Caption {
            get {
                return ResourceManager.GetString("Sync_Dialog_UploadAll_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to upload all new Multimedia? Only do this if the Phone is charging and connected via Wifi. ähnelt.
        /// </summary>
        public static string Sync_Dialog_UploadAll_Text {
            get {
                return ResourceManager.GetString("Sync_Dialog_UploadAll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die data ähnelt.
        /// </summary>
        public static string Sync_Header_Data {
            get {
                return ResourceManager.GetString("Sync_Header_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die multimedia ähnelt.
        /// </summary>
        public static string Sync_Header_Multimedia {
            get {
                return ResourceManager.GetString("Sync_Header_Multimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t download another taxon list. ähnelt.
        /// </summary>
        public static string TaxonManagement_Message_CantDownload {
            get {
                return ResourceManager.GetString("TaxonManagement_Message_CantDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string TaxonManagement_Message_Error {
            get {
                return ResourceManager.GetString("TaxonManagement_Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die download all ähnelt.
        /// </summary>
        public static string TaxonManagement_Title_DownloadAll {
            get {
                return ResourceManager.GetString("TaxonManagement_Title_DownloadAll", resourceCulture);
            }
        }
    }
}
